
# This script creates real named users in the previous 4 OUs 
# Author: Generated by AI, Adapted by myself for my lab .

$DomainDN = (Get-ADDomain).DistinguishedName

# Each OU with its real user names
$OUUsers = @(
    @{ OU = "OU=Reception,$DomainDN";      Users = @("Jean","Jeanne","Jinette","Julien","Juliette") }
    @{ OU = "OU=Nursing,$DomainDN";        Users = @("Ben","Boris","Bibata","Brenda","Brigitte") }
    @{ OU = "OU=Administration,$DomainDN"; Users = @("Grace","Gregoire","Gaston","Gloria","Gladys") }
    @{ OU = "OU=IT Department,$DomainDN";  Users = @("Franck","Francine","Fidelia","Flore") }
)

# Shared temporary password
$Password = ConvertTo-SecureString "Password123!" -AsPlainText -Force

Import-Module ActiveDirectory

foreach ($Entry in $OUUsers) {

    $OUPath = $Entry.OU
    $OUName = ($OUPath -split ',')[0].Replace("OU=", "")

    Write-Host "Processing OU: $OUName" -ForegroundColor Cyan

    # Safely verify if the OU already exists

    if (-not (Get-ADOrganizationalUnit -Filter "DistinguishedName -eq '$OUPath'" -ErrorAction SilentlyContinue)) {
        Write-Host "Error: OU '$OUName' does not exist. Skipping." -ForegroundColor Red
        continue
    }

    foreach ($FirstName in $Entry.Users) {

        $SamAccountName = $FirstName.ToLower()
        $DisplayName    = $FirstName

        # Check if user already exists
        if (Get-ADUser -Filter "SamAccountName -eq '$SamAccountName'" -ErrorAction SilentlyContinue) {
            Write-Host "Skipping: '$SamAccountName' already exists." -ForegroundColor Yellow
        } else {
            try {
                New-ADUser -Name $DisplayName `
                           -SamAccountName $SamAccountName `
                           -Path $OUPath `
                           -AccountPassword $Password `
                           -ChangePasswordAtLogon $true `
                           -Enabled $true `
                           -ErrorAction Stop

                Write-Host "Success: Created '$SamAccountName' in $OUName" -ForegroundColor Green
            }
            catch {
                Write-Error "Failed to create '$SamAccountName': $_"
            }
        }
    }
}