# This script is write to create 4 different OUs
# Author :  It has been generated by AI and I've adapted it
 to my purpose .

$DomainDN = (Get-ADDomain).DistinguishedName

# List of OUs to create (Name = OU Name, Path = Parent DN)
$OUList = @(
    @{ Name = "Reception";      Path = $DomainDN }
    @{ Name = "Nursing";        Path = $DomainDN }
    @{ Name = "Administration"; Path = $DomainDN }
    @{ Name = "IT Department";  Path = $DomainDN }
)


# Import the Active Directory module

Import-Module ActiveDirectory

foreach ($OU in $OUList) {
    # Construct the full Distinguished Name for verification
    $TargetDN = "OU=$($OU.Name),$($OU.Path)"
    
    # Check if the OU already exists
    if (Get-ADOrganizationalUnit -Filter "DistinguishedName -eq '$TargetDN'" -ErrorAction SilentlyContinue) {
        Write-Host "Skipping: OU '$($OU.Name)' already exists at target path." -ForegroundColor Yellow
    } else {
        try {
            # Create the OU with accidental deletion protection enabled
            New-ADOrganizationalUnit -Name $OU.Name -Path $OU.Path -ProtectedFromAccidentalDeletion $true -ErrorAction Stop
            Write-Host "Success: Created OU '$($OU.Name)'" -ForegroundColor Green
        }
        catch {
            Write-Error "Failed to create OU '$($OU.Name)': $_"
        }
    }
}
